const SUPABASE_URL = 'https://hamsvtciocwsfrmrsphk.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhbXN2dGNpb2N3c2ZybXJzcGhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUxOTU5MDUsImV4cCI6MjEwMDc3MTkwNX0.yK_O98XfvQhwEc6S90j2ZjDmE2jrdQSN2-BEWnmaraw';

const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
